#-------------------------------------------------------------------
# The contents of this file are placed in the public domain. Feel
# free to make use of it in any way you like.
#-------------------------------------------------------------------

macro( setupLibevent LIBEVENT_SOURCE, LIBEVENT_BINARIES, LIBEVENT_LIBRARIES )

# Guess the paths.
set( LIBEVENT_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}/Dependencies/libevent" CACHE STRING "Path to libevent source code (grab from git://levent.git.sourceforge.net/gitroot/levent/libevent)" )
if( WIN32 )
	set( LIBEVENT_BINARIES "${LIBEVENT_SOURCE}/build" CACHE STRING "Path to libevent's build folder generated by CMake" )
	link_directories( "${LIBEVENT_BINARIES}/lib/$(ConfigurationName)" )
else()
	set( LIBEVENT_BINARIES "${LIBEVENT_SOURCE}/build/${CMAKE_BUILD_TYPE}" CACHE STRING "Path to libevent's build folder generated by CMake" )
	link_directories( "${LIBEVENT_BINARIES}/lib" )
endif()

# libevent config
include_directories( "${LIBEVENT_BINARIES}/include" )

# libevent includes
include_directories( "${LIBEVENT_SOURCE}/include" )

set( LIBEVENT_LIBRARIES
	event
	event_core
	event_extra
	)

endmacro()
